CREATE TABLE IF NOT EXISTS assignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  period_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT DEFAULT NULL,
  workflow_status TEXT NOT NULL DEFAULT 'NOT_DICTATED' CHECK (
    workflow_status IN ('NOT_DICTATED', 'WAITING_FOR_STUDENTS', 'WAITING_FOR_CORRECTION')
  ),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  deletedAt DATETIME DEFAULT NULL,
  FOREIGN KEY(period_id) REFERENCES periods(id) ON DELETE CASCADE
);
