CREATE TABLE IF NOT EXISTS deliveries (
  assignment_id INTEGER NOT NULL,
  student_id INTEGER NOT NULL,
  workflow_status TEXT NOT NULL DEFAULT 'NOT_DICTATED' CHECK (
    workflow_status IN ('NOT_DICTATED', 'WAITING_FOR_STUDENTS', 'WAITING_FOR_CORRECTION', 'APPROVED', 'REJECTED')
  ),
  grade REAL DEFAULT 0,
  ai_level INTEGER DEFAULT 0,
  comments TEXT DEFAULT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  deletedAt DATETIME DEFAULT NULL,
  PRIMARY KEY(assignment_id, student_id),
  FOREIGN KEY(assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
  FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE
);
